import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Blocks, BrainCircuit, ExternalLink, Github, GraduationCap, Network } from "lucide-react";

const projects = [
  { title: "System Design Simulator", description: "An interactive simulator for distributed architectures that models real M/M/c queues instead of fake loading animations.", icon: Network, technologies: ["Next.js", "React", "React Flow", "Queueing Theory", "OpenAI API"], highlights: ["Poisson-arrival traffic simulation", "Little's Law latency modeling", "p50/p95/p99 latency charts", "Node-failure cascades and request drops"], liveDemo: "https://system-desisn-simulator.vercel.app/", github: "https://github.com/CoderRdm/System_Desisn-Simulator", color: "bg-primary" },
  { title: "AgentAudit", description: "An LLM-agent hallucination and failure-detection system that evaluates generated summaries against source documents.", icon: BrainCircuit, technologies: ["Python", "Groq API", "Llama 3.3 70B", "Streamlit"], highlights: ["45+ structured agent evaluations", "Hallucination-rate measurement", "Task-coverage analysis", "Secondary-LLM fact checking"], liveDemo: "#", github: "https://github.com/CoderRdm/AI_obeserve", color: "bg-accent" },
  { title: "NightOwl", description: "An adaptive learning platform with AI-driven level assessment, personalized tutoring, study planning, and certification capabilities.", icon: GraduationCap, technologies: ["React", "TypeScript", "Google GenAI", "Vite"], highlights: ["Personalized seven-day study plans", "AI-generated assessments", "Multilingual tutoring", "Optional voice interaction"], liveDemo: "#", github: "https://github.com/CoderRdm/Gemini-Hackathon", color: "bg-primary" },
  { title: "Product Lifecycle Tracker", description: "A Solidity smart-contract project for recording products and their lifecycle checkpoints on-chain.", icon: Blocks, technologies: ["Solidity"], highlights: ["Product creation", "Lifecycle checkpoint records", "Location and description fields", "On-chain history retrieval"], liveDemo: "#", github: "https://github.com/CoderRdm/sparkathon", color: "bg-accent" },
];

const Projects = () => (
  <section id="projects" className="section-padding bg-background"><div className="max-w-7xl mx-auto"><div className="text-center mb-16"><h2 className="text-4xl md:text-5xl font-bold mb-4">Featured <span className="text-primary">Projects</span></h2><p className="text-lg text-muted-foreground max-w-3xl mx-auto">A selection of AI, systems, and blockchain projects I have built.</p><div className="w-24 h-0.5 bg-primary mx-auto mt-6" /></div><div className="grid lg:grid-cols-2 gap-8">
    {projects.map((project) => { const Icon = project.icon; return <Card key={project.title} className="card-hover border-2 h-full flex flex-col"><div className="p-8 flex flex-col flex-1"><div className="flex items-center mb-6"><div className={`p-4 rounded-xl ${project.color} mr-4 shadow-lg`}><Icon className="h-6 w-6 text-white" /></div><h3 className="text-2xl font-bold text-foreground">{project.title}</h3></div><p className="text-muted-foreground mb-6 leading-relaxed text-base flex-1">{project.description}</p><div className="space-y-3 mb-6"><h4 className="font-semibold text-foreground text-sm uppercase tracking-wide">Key Features</h4><div className="grid grid-cols-2 gap-3">{project.highlights.map((highlight) => <div key={highlight} className="flex items-start gap-2"><div className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" /><span className="text-sm text-muted-foreground leading-relaxed">{highlight}</span></div>)}</div></div><div className="flex flex-wrap gap-2 mb-6">{project.technologies.map((tech) => <Badge key={tech} variant="secondary" className="px-3 py-1.5 text-xs font-medium">{tech}</Badge>)}</div><div className="flex gap-4 mt-auto"><Button size="lg" className="flex-1 font-semibold" onClick={() => project.liveDemo === "#" ? alert("Live demo not available right now") : window.open(project.liveDemo, "_blank")}><ExternalLink className="mr-2 h-4 w-4" />Live Demo</Button><Button variant="outline" size="lg" className="flex-1 font-semibold" onClick={() => window.open(project.github, "_blank")}><Github className="mr-2 h-4 w-4" />GitHub</Button></div></div></Card>; })}
  </div></div></section>
);

export default Projects;
